#ifndef QTCOMPOSITION_GLOBAL_H
#define QTCOMPOSITION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTCOMPOSITION_LIBRARY)
#  define QTCOMPOSITION_EXPORT Q_DECL_EXPORT
#else
#  define QTCOMPOSITION_EXPORT Q_DECL_IMPORT
#endif

#endif // QTCOMPOSITION_GLOBAL_H
